export const sections = {
    Noticias: [
      'Política',
      'Investigación',
      'Bogotá',
      'Judicial',
      'Salud',
      'Actualidad',
      'Alto Turmequé',
      'Medio Ambiente',
      'El Mundo',
      'Eduación',
      'Paz',
      'Nacional',
      'Ciencias',
      'Redes Sociales',
    ],
    Opinión: [],
    Economía: [],
    Deportes: [
      'Fútbol Colombiano',
      'Fútbol internacional',
      'Ciclismo',
      'Automovilismo',
      'Baloncesto',
      'Besibol',
      'Golf',
      'Tenis',
      'Fútbol pot TV',
    ],
    Entretenimiento: ['Cine', 'Eventos', 'Gente', 'Medios', 'Música'],
    Cultura: [],
    Cromos: [
      'Estilo de vida',
      'Moda',
      'Gastronomía',
      'vida Social',
      'Maternidad y Bienestar',
      'Astrología',
      'Columnistas',
    ],
    Tecnología: [],
    Blogs: [],
    'Colombia 2020': [
      'inicio',
      'Poodcast',
      'Debate',
      'Territorio',
      'Justicia',
      'Opinión',
      'País',
      'Pedagogía',
    ],
    Especiales: ['Autos', 'Mundos Distintos'],
  };